### ISSUE TITLE
from Fauconnier and Turner's "The Way We Think"

### ISSUE THREAD

**Issue by panicz** [hypotext/notation#15]
Here's a fragment from the book "The Way We Think" you may like (unfortunately, it isn't freely available AFAIK)

  The development of formal systems to leverage human invention
  and insight has been a painful, centuries-long process. [...]
  In the twelfth century, the Hindu mathematician Bhaskara said,
  ``The root of the root of the quotient of the greater irrational
  divided by the lesser one being increased by one; the sum being
  squared and multiplied by the smaller irrational quantity is the
  sum of the two surd roots.'' This we would now express in the form
  of an equation, using the much more systematically manageable set
  of formal symbols shown below. This equation by itself looks no
  less opaque than Bhaskara's description, but the notation immediately
  connects it to a large system of such equations in ways that
  make it easy to manipulate.
  \begin{equation*}
    \sqrt{(\sqrt{\frac{n}{k}}+1)^{2}k}=\sqrt{k}+\sqrt{n}
  \end{equation*}

**Comment by hypotext** [comment]
I agree that going from natural language to algebra is a major notational advance. Want to make a PR adding this quote? (The book is now on my to-read list too.)

**Comment by panicz** [comment]
I guess I could do that, but I don't know what to do about the fact that all the other quotes have links to the resources they come from (some of them are dead links, but none links to amazon -- I understand that we don't want to make this resource an advertisement)

**Comment by hypotext** [comment]
It's fine to link either to [this PDF of chapter 1](http://www.cogsci.ucsd.edu/~nunez/COGS152_S12/TWWT_Ch1.pdf), or the [quote in Google Books](https://books.google.com/books?id=FdOLriVyzwkC&pg=PA10&lpg=PA10&dq=This+equation+by+itself+looks+no+less+opaque+than+Bhaskaras+description,+but+the+notation+immediately+connects+it+to+a+large+system+of+such+equations+in+ways+that+make+it+easy+to+manipulate.&source=bl&ots=4xhBc_YSbz&sig=PgTwMKCWlsl_alAYnVl5W9bUCP0&hl=en&sa=X&ved=0ahUKEwjpuvWZsLvWAhWI4iYKHfTHAsUQ6AEIKjAA#v=onepage&q=This%20equation%20by%20itself%20looks%20no%20less%20opaque%20than%20Bhaskaras%20description%2C%20but%20the%20notation%20immediately%20connects%20it%20to%20a%20large%20system%20of%20such%20equations%20in%20ways%20that%20make%20it%20easy%20to%20manipulate.&f=false).

**Comment by panicz** [comment]
https://github.com/hypotext/notation/pull/16
