### ISSUE TITLE
Illegal instruction: 4 when trying to install TidalCycles

### ISSUE THREAD

**Issue by 001ok** [hypotext/notation#17]
I'm having difficult installing tidal cycles from my terminal command

Have even followed the path through HomeBrew, which installs everything but Tidal

Following the instructions, i keep getting the 'Illegal instruction: 4' message in my terminal window

I'm running on os x 10.9.5 could this be a problem?

Can anyone help?

**Comment by hypotext** [comment]
I suggest opening an issue here. https://github.com/tidalcycles/Tidal
