### ISSUE TITLE
A few possible additions?

### ISSUE THREAD

**Issue by JobLeonard** [hypotext/notation#3]
https://www.ted.com/talks/robert_lang_folds_way_new_origami?language=en

Robert Lang talks about the math of origami, but also specifically about how the ability to write down origami instructions greatly accelerated the development of the hobby because easy sharing and tweaking of ideas was made possible

https://www.youtube.com/watch?v=sULa9Lc4pck

3Blue1Brown's youtube video on the "Triangle of Power" and how it is much better at showing the symmetrical *and* asymmetrical relationships between powers, roots and logarithms.

**Comment by hypotext** [comment]
Both are great suggestions; thanks! I plan to watch Lang's talk and add some quotes. Multiple other people have also suggested the Triangle of Power video. :)

**Comment by hypotext** [comment]
Added Triangle of Power, thanks!
