### ISSUE TITLE
to add some quotes from Jacques Derrida ?

### ISSUE THREAD

**Issue by xieyuheng** [hypotext/notation#4]
I like this repo very much :)
Derrida also has some intriguing thoughts about language.
If you read Derrida and you find some of his thoughts enlightening,
then add some quotes from Derrida will be helpful to balance Ted Chiang's highly offensive view toward Chinese.

**Comment by hypotext** [comment]
Thanks for the suggestion! I'm not familiar with Derrida's work; could you suggest some quotes?

**Comment by xieyuheng** [comment]
hi hypotext, thanks for your reply (^-^)

I love languages so much ~
so I decide to create a fork of your repo.

I have too many things to add, I think my fork will be a fork-away fork ~
In particular, I will show why Chinese is not a 'bad' language as your repo indicated.

I will surely add quotes from Jacques Derrida, and I am closing this issue now,
but whenever I have something worth sharing to you, I will leave comment in this issue :)

**Comment by hypotext** [comment]
That's great! Looking forward to reading your version.
